name: build
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  generate-data:
    runs-on: ubuntu-latest
    container:
      image: earthly/dind:ubuntu
      options: --privileged
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: python -m pip install Jinja2 docker
      - name: Build container images
        run: python -m containers.build
      - name: Generate data
        run: |
          cd ${{ github.workspace }}
          python python/generate-data.py
          python -m zipfile -c image-data.zip python/.data/*
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: containers/out/logs
        if: always()
      - name: Upload image data
        uses: actions/upload-artifact@v4
        with:
          name: image-data
          path: image-data.zip
