name: docs
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: earthly/dind:ubuntu
      options: --privileged
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: Checkout docs branch
        uses: actions/checkout@v4
        with:
          ref: docs
          path: docs
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: python -m pip install -r main/.github/workflows/requirements.txt
      - name: Build container images
        run: python -m containers.build
        env:
          PYTHONPATH: ${{ github.workspace }}/main
      - name: Generate data
        run: |
          cd ${{ github.workspace }}/main
          python python/generate-data.py
      - name: Build Documentation
        run: sphinx-build -n main/docs docs
        env:
          PYTHONPATH: ${{ github.workspace }}/main
      - name: Setup git
        run: |
          git config --global user.email actions@github.com
          git config --global user.name 'Github Actions'
          git config --global core.editor true
      - name: Commit documentation changes
        run: |
          cd ${{ github.workspace }}/docs
          git add -u
          git add .nojekyll *
          git commit --fixup HEAD || true
          git rebase -i --autosquash --root
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs
          directory: docs
          force: true
