name: docs
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: earthly/dind:ubuntu
      options: --privileged
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: python -m pip install -r .github/workflows/requirements.txt
      - name: Build container images
        run: python -m containers.build
        env:
          PYTHONPATH: ${{ github.workspace }}
      - name: Generate data
        run: |
          cd ${{ github.workspace }}
          python python/generate-data.py
      - name: Build Documentation
        run: sphinx-build -n docs docs/out
        env:
          PYTHONPATH: ${{ github.workspace }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/out
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
