name: release
on:
  push:
    tags:
      - '*'

jobs:
  build-release-artifacts:
    runs-on: ubuntu-latest
    container:
      image: earthly/dind:ubuntu
      options: --privileged
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    environment:
      name: pypi
      url: https://pypi.org/p/python-environments
    permissions:
      id-token: write
    env:
      DOCKER_CONFIG: ${{ github.workspace }}/.docker-config.json
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: quay.io
          username: python-environments+github_actions
          password: ${{ secrets.QUAY_IO_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: |
          python -m pip install virtualenv build
          python -m build --version
      - name: Build release artifacts
        run: |
          cd ${{ github.workspace }}
          git config --global --add safe.directory ${{ github.workspace }}
          python -m build \
              -Csetup-args=-Dpush_containers=true \
              -Csetup-args=-Dcontainers_build_path=${{ github.workspace }}/containers/out \
              -Cbuilddir=builddir
      - uses: pypa/gh-action-pypi-publish@release/v1
      - uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            containers/out/logs
            builddir/meson-logs
        if: always()
